services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tumbot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      BOT_DB: /data/bot.db
      TZ: America/New_York
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      TELEGRAM_LINK_SECRET: "${TELEGRAM_LINK_SECRET}"
    volumes:
      - /var/lib/tumbot/data:/data
    networks:
      - tumbot_net
    stdin_open: true
    tty: true

networks:
  tumbot_net:
    name: tumbot_net
    driver: bridge
